languageCode = 'fi-FI'
title = 'Vihre√§t vaalikonevastaukset'
theme = 'whiteplain'
sectionPagesMenu = 'main'
[params]
    showShareIcons = false  

[menus]
  [[menus.main]]
    name = 'HS, Aamulehti'
    pageRef = '/HS__AL'
    weight = 20
  [[menus.main]]
    name = 'HS, AL ja SK'
    pageRef = '/HS__AL__SK'
    weight = 30
  [[menus.main]]
    name = 'Iltalehti'
    pageRef = '/IL'
    weight = 40
  [[menus.main]]
    name = 'Ilta-Sanomat'
    pageRef = '/IS'
    weight = 50
  [[menus.main]]
    name = 'Teemat'
    pageRef = '/tags'
    weight = 60